version: '3.8'

services:
  mysql-container:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_DATABASE: base_final
      MYSQL_USER: user1
      MYSQL_PASSWORD: alexoberco1A@
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend-container:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-container
    depends_on:
      - mysql-container
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: default

volumes:
  mysql_data:
